// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByVBOX2eYCgcB3IQ0kD1VOg2b0TUUHbJw',
    appId: '1:805723378810:web:d05a06adc596f1537217c3',
    messagingSenderId: '805723378810',
    projectId: 'movie-app-e8f16',
    authDomain: 'movie-app-e8f16.firebaseapp.com',
    storageBucket: 'movie-app-e8f16.appspot.com',
    measurementId: 'G-PLSL77X8Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdwYlCazRYJTHIllTr5zLTdGzUUvJ5OWA',
    appId: '1:805723378810:android:56ec248602724fce7217c3',
    messagingSenderId: '805723378810',
    projectId: 'movie-app-e8f16',
    storageBucket: 'movie-app-e8f16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATeFi7B1x2V1eam7p4DfW0OBbws4eyfV4',
    appId: '1:805723378810:ios:da8215e1a0957c9e7217c3',
    messagingSenderId: '805723378810',
    projectId: 'movie-app-e8f16',
    storageBucket: 'movie-app-e8f16.appspot.com',
    iosBundleId: 'com.example.movieAppFinal',
  );
}
